(cl:in-package ASV-msg)
(cl:export '(HEADING-VAL
          HEADING
          ROLL-VAL
          ROLL
          PITCH-VAL
          PITCH
          PITCH_DER-VAL
          PITCH_DER
          TEMPERATURE-VAL
          TEMPERATURE
          DEPTH-VAL
          DEPTH
          M-VAL
          M
          MX-VAL
          MX
          MY-VAL
          MY
          MZ-VAL
          MZ
          A-VAL
          A
          AX-VAL
          AX
          AY-VAL
          AY
          AZ-VAL
          AZ
))