/* Auto-generated by genmsg_cpp for file /home/gdp40/fuerte_workspace/sandbox/ASV/msg/arduino.msg */
#ifndef ASV_MESSAGE_ARDUINO_H
#define ASV_MESSAGE_ARDUINO_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace ASV
{
template <class ContainerAllocator>
struct arduino_ {
  typedef arduino_<ContainerAllocator> Type;

  arduino_()
  : battery_voltage(0.0)
  , prop_demand(0.0)
  , voltage_demand(0.0)
  {
  }

  arduino_(const ContainerAllocator& _alloc)
  : battery_voltage(0.0)
  , prop_demand(0.0)
  , voltage_demand(0.0)
  {
  }

  typedef float _battery_voltage_type;
  float battery_voltage;

  typedef float _prop_demand_type;
  float prop_demand;

  typedef float _voltage_demand_type;
  float voltage_demand;


  typedef boost::shared_ptr< ::ASV::arduino_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ASV::arduino_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct arduino
typedef  ::ASV::arduino_<std::allocator<void> > arduino;

typedef boost::shared_ptr< ::ASV::arduino> arduinoPtr;
typedef boost::shared_ptr< ::ASV::arduino const> arduinoConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::ASV::arduino_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::ASV::arduino_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace ASV

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::ASV::arduino_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::ASV::arduino_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::ASV::arduino_<ContainerAllocator> > {
  static const char* value() 
  {
    return "c206d8bc0371a0b0ba4915d805666d5f";
  }

  static const char* value(const  ::ASV::arduino_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xc206d8bc0371a0b0ULL;
  static const uint64_t static_value2 = 0xba4915d805666d5fULL;
};

template<class ContainerAllocator>
struct DataType< ::ASV::arduino_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ASV/arduino";
  }

  static const char* value(const  ::ASV::arduino_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::ASV::arduino_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float32 battery_voltage\n\
float32 prop_demand\n\
float32 voltage_demand\n\
\n\
";
  }

  static const char* value(const  ::ASV::arduino_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::ASV::arduino_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::ASV::arduino_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.battery_voltage);
    stream.next(m.prop_demand);
    stream.next(m.voltage_demand);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct arduino_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ASV::arduino_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::ASV::arduino_<ContainerAllocator> & v) 
  {
    s << indent << "battery_voltage: ";
    Printer<float>::stream(s, indent + "  ", v.battery_voltage);
    s << indent << "prop_demand: ";
    Printer<float>::stream(s, indent + "  ", v.prop_demand);
    s << indent << "voltage_demand: ";
    Printer<float>::stream(s, indent + "  ", v.voltage_demand);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ASV_MESSAGE_ARDUINO_H

