/* Auto-generated by genmsg_cpp for file /home/gdp40/fuerte_workspace/sandbox/ASV/msg/headingd.msg */
#ifndef ASV_MESSAGE_HEADINGD_H
#define ASV_MESSAGE_HEADINGD_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace ASV
{
template <class ContainerAllocator>
struct headingd_ {
  typedef headingd_<ContainerAllocator> Type;

  headingd_()
  : heading_demand(0.0)
  {
  }

  headingd_(const ContainerAllocator& _alloc)
  : heading_demand(0.0)
  {
  }

  typedef float _heading_demand_type;
  float heading_demand;


  typedef boost::shared_ptr< ::ASV::headingd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ASV::headingd_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct headingd
typedef  ::ASV::headingd_<std::allocator<void> > headingd;

typedef boost::shared_ptr< ::ASV::headingd> headingdPtr;
typedef boost::shared_ptr< ::ASV::headingd const> headingdConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::ASV::headingd_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::ASV::headingd_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace ASV

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::ASV::headingd_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::ASV::headingd_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::ASV::headingd_<ContainerAllocator> > {
  static const char* value() 
  {
    return "a033fb24cad4dc624033484eb21eea63";
  }

  static const char* value(const  ::ASV::headingd_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xa033fb24cad4dc62ULL;
  static const uint64_t static_value2 = 0x4033484eb21eea63ULL;
};

template<class ContainerAllocator>
struct DataType< ::ASV::headingd_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ASV/headingd";
  }

  static const char* value(const  ::ASV::headingd_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::ASV::headingd_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float32 heading_demand\n\
\n\
\n\
";
  }

  static const char* value(const  ::ASV::headingd_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::ASV::headingd_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::ASV::headingd_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.heading_demand);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct headingd_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ASV::headingd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::ASV::headingd_<ContainerAllocator> & v) 
  {
    s << indent << "heading_demand: ";
    Printer<float>::stream(s, indent + "  ", v.heading_demand);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ASV_MESSAGE_HEADINGD_H

