/* Auto-generated by genmsg_cpp for file /home/gdp40/fuerte_workspace/sandbox/ASV/msg/status.msg */
#ifndef ASV_MESSAGE_STATUS_H
#define ASV_MESSAGE_STATUS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace ASV
{
template <class ContainerAllocator>
struct status_ {
  typedef status_<ContainerAllocator> Type;

  status_()
  : nodeID(0)
  , status(false)
  {
  }

  status_(const ContainerAllocator& _alloc)
  : nodeID(0)
  , status(false)
  {
  }

  typedef int32_t _nodeID_type;
  int32_t nodeID;

  typedef uint8_t _status_type;
  uint8_t status;


  typedef boost::shared_ptr< ::ASV::status_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ASV::status_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct status
typedef  ::ASV::status_<std::allocator<void> > status;

typedef boost::shared_ptr< ::ASV::status> statusPtr;
typedef boost::shared_ptr< ::ASV::status const> statusConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::ASV::status_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::ASV::status_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace ASV

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::ASV::status_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::ASV::status_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::ASV::status_<ContainerAllocator> > {
  static const char* value() 
  {
    return "722a3850d404093d2b94283695c2a465";
  }

  static const char* value(const  ::ASV::status_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x722a3850d404093dULL;
  static const uint64_t static_value2 = 0x2b94283695c2a465ULL;
};

template<class ContainerAllocator>
struct DataType< ::ASV::status_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ASV/status";
  }

  static const char* value(const  ::ASV::status_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::ASV::status_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int32 nodeID\n\
bool status\n\
\n\
";
  }

  static const char* value(const  ::ASV::status_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::ASV::status_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::ASV::status_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.nodeID);
    stream.next(m.status);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct status_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ASV::status_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::ASV::status_<ContainerAllocator> & v) 
  {
    s << indent << "nodeID: ";
    Printer<int32_t>::stream(s, indent + "  ", v.nodeID);
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ASV_MESSAGE_STATUS_H

